project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: euro2024.png
  navbar:
    logo: euro2024.png
    left:
      - href: index.qmd
        text: Home
      - text: Recipe
        href: recipe.qmd
      - text: Hobbies
        href: hobbies.qmd
      - text: Reflection
        href: reflection.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



